{{- if and .Values.ingress .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "product-api.fullname" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range $h := (.Values.ingress.hosts | default list) }}
    - host: {{ $h.host | quote }}
      http:
        paths:
          {{- range $p := ($h.paths | default list) }}
          - path: {{ $p.path | default "/" }}
            pathType: {{ $p.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "product-api.fullname" $ }}
                port:
                  number: {{ $.Values.service.port | default 80 }}
          {{- end }}
    {{- end }}
{{- end }}
