apiVersion: v1
kind: Service
metadata:
  name: {{ include "product-api.fullname" . }}
spec:
  selector:
    app: {{ include "product-api.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 8000 }}
  type: ClusterIP
