name: Build and Push Docker Images

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_TOKEN }}

      - name: Build & Push product-api
        run: |
          docker build -t ghcr.io/vpydikondala/product-api:${{ github.sha }} ./apps/product-api
          docker push ghcr.io/vpydikondala/product-api:${{ github.sha }}
