name: Update Helm Values in Infra

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types: [completed]
  workflow_dispatch:

jobs:
  update-helm-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false   # Disable automatic token to avoid 403 errors

      - name: Configure git to use PAT for authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_TOKEN }}@github.com/vpydikondala/argocd.git
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Commit and Push changes
        run: |
          git add infra/charts/product-api/values.yaml
          git diff --cached --quiet || git commit -m "Update image tag to ${{ github.sha }}"
          git push origin HEAD:main